name: sitename
type: silverstripe
docroot: public
php_version: "8.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_fqdns: []
database:
    type: mariadb
    version: "10.4"
web_environment: []
upload_dirs:
    - "assets"
nodejs_version: "18"
web_extra_exposed_ports:
    - name: Vite Dev Server
      container_port: 5173
      http_port: 5173
      https_port: 5174
    - name: Storybook
      container_port: 6006
      http_port: 6006
      https_port: 6007
# hooks:
#  post-start:
#    - exec: "yarn && yarn storybook && yarn dev"
